# -*- coding: utf-8 -*-
"""Untitled121.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L3Ktik6bvbA0zyMQlDKl3GoUiETdH331
"""



import openai
import streamlit as st

openai.api_key = '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'

def main():
  st.markdown("<h1 style = 'text-align: center; color: red;'> Netcoder ChatGPT </h1>", unsafe_allow_html = True )
  st.sidebar.info('Netcoder Assistance to generate Content')
  st.sidebar.info('Start with the option \n Before you proceed to the next')
  op = st.sidebar.selectbox('Steps', ['topics', 'section', 'content'])
  if op == 'topics':
    topics()

def BlogTopics(prompt):
  response = openai.Completion.create(engine = 'davinci-instruct-beta-v3', prompt = prompt, temperature = 0.7, max_tokens = 100, top_p = 1,frequency_penalty = 0, presence_penalty = 0)
  return response.choices[0].text

def topics():
  st.info("To generate the topic please follow the pattern below")
  prompt = st.text_area('Write your words', height = 50, value = 'Generate your topic on data science with Python')
  if st.button('Send'):
    st.text(BlogTopics(prompt))